name: openbind-analysis

channels:
  - conda-forge

dependencies:
  - python=3.12
  - numpy=1.26.4
  - pandas=2.3.3
  - scipy
  - matplotlib-base=3.10.9
  - freetype=2.14.3
  - pillow=12.2.0
  - pyarrow
  - rdkit=2025.03.6
  - scikit-learn
  - umap-learn
  - tqdm